### ISSUE TITLE
IndexError: index 485 is out of bounds for axis 0 with size 485

### ISSUE THREAD

**Issue by loserben** [pnpsuM/SOH_Est_CNN-LSTM#1]
![image](https://user-images.githubusercontent.com/52242115/223901562-657b167a-82bb-40b6-8163-dbbef20be536.png)

**Comment by pnpsuM** [comment]
Can I get the details of how you set the parameters? especially I don't get the 'sample_len' parameter.
Maybe that changed the length of the y_graph I guess.

**Comment by loserben** [comment]
> Can I get the details of how you set the parameters? especially I don't get the 'sample_len' parameter. Maybe that changed the length of the y_graph I guess.

 I don't change parameters
![image](https://user-images.githubusercontent.com/52242115/223907445-4e4e5797-de6e-4d14-a5ec-5d01dcbdf68d.png)

**Comment by pnpsuM** [comment]
![image](https://user-images.githubusercontent.com/89827636/223917312-29c6fd5d-d3e0-410e-a225-0d7ea83feba7.png)
When I run the code with hyperparameters you sent, it works normally.

**Comment by loserben** [comment]
when I run the code CNN-LSTM_SOH_Epoch, got this

![image](https://user-images.githubusercontent.com/52242115/223938456-8e4c84d4-aa94-464f-9524-8f94febe31e9.png)

**Comment by pnpsuM** [comment]
![image](https://user-images.githubusercontent.com/89827636/223940632-1fcbb03a-6a92-4018-8565-abebc78439b7.png)
Now I get it. I edited the code so that it works fine.

*_Epoch.ipynb code was for tuning epochs parameter, and its model is set to output (None, None, 1) shaped tensor.
And after some experiment, other codes' models were modified to return (None, 1) shaped tensor[image above], so the SOH_func_scaler.py was updated too. And I forgot to update the *_Epoch code. 

Thanks for your notification.

**Comment by loserben** [comment]
> ![image](https://user-images.githubusercontent.com/89827636/223940632-1fcbb03a-6a92-4018-8565-abebc78439b7.png) Now I get it. I edited the code so that it works fine.
> 
> *_Epoch.ipynb code was for tuning epochs parameter, and its model is set to output (None, None, 1) shaped tensor. And after some experiment, other codes' models were modified to return (None, 1) shaped tensor[image above], so the SOH_func_scaler.py was updated too. And I forgot to update the *_Epoch code.
> 
> Thanks for your notification.

No thanks , and the code CNN-LSTM_SOH.ipynb have the same problem!
